# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c85bfe612b5a6650735fd1cd36fb85c1ba8de2cfd8a7f6d126a102ed330aac680ff7a0a555c41b6d426be129592224ee96bf07b87a412459a27a6ef2d20397a6
  email: niritest0@gmail.com
  password: 9915216404
  local_url: http://localhost:3000
  my_mac_url: http://192.168.33.10:3000
  ubuntu_url: http://192.168.3.3:3000
test:
  secret_key_base: 3c27ae83b816117967870c310c15181dd94f1b2e4990d7cc54f3314c98835a8805e8173342f05eb4c0ddd589273aa37da81658288d172b27f4de806a926fa65a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
